set(_AMENT_PACKAGE_NAME "ar3_description")
set(ar3_description_VERSION "0.0.0")
set(ar3_description_MAINTAINER "cobot <zchampion2020@my.fit.edu>")
set(ar3_description_BUILD_DEPENDS )
set(ar3_description_BUILDTOOL_DEPENDS "ament_cmake")
set(ar3_description_BUILD_EXPORT_DEPENDS )
set(ar3_description_BUILDTOOL_EXPORT_DEPENDS )
set(ar3_description_EXEC_DEPENDS )
set(ar3_description_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(ar3_description_GROUP_DEPENDS )
set(ar3_description_MEMBER_OF_GROUPS )
set(ar3_description_DEPRECATED "")
set(ar3_description_EXPORT_TAGS)
list(APPEND ar3_description_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
