set(_AMENT_PACKAGE_NAME "ar3_bringup")
set(ar3_bringup_VERSION "0.0.0")
set(ar3_bringup_MAINTAINER "Zach Champion <zchampion2020@my.fit.edu>")
set(ar3_bringup_BUILD_DEPENDS )
set(ar3_bringup_BUILDTOOL_DEPENDS "ament_cmake")
set(ar3_bringup_BUILD_EXPORT_DEPENDS )
set(ar3_bringup_BUILDTOOL_EXPORT_DEPENDS )
set(ar3_bringup_EXEC_DEPENDS "ar3_moveit_config" "joy")
set(ar3_bringup_TEST_DEPENDS )
set(ar3_bringup_GROUP_DEPENDS )
set(ar3_bringup_MEMBER_OF_GROUPS )
set(ar3_bringup_DEPRECATED "")
set(ar3_bringup_EXPORT_TAGS)
list(APPEND ar3_bringup_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
