set(_AMENT_PACKAGE_NAME "aruco_transforms")
set(aruco_transforms_VERSION "0.0.0")
set(aruco_transforms_MAINTAINER "zachc <zachchampion79@gmail.com>")
set(aruco_transforms_BUILD_DEPENDS "tf2" "tf2_geometry_msgs" "geometry_msgs" "tf2_ros" "cv_bridge" "image_transport" "pluginlib" "rosidl_default_generators" "sensor_msgs" "generate_parameter_library")
set(aruco_transforms_BUILDTOOL_DEPENDS "ament_cmake")
set(aruco_transforms_BUILD_EXPORT_DEPENDS "tf2" "tf2_geometry_msgs" "geometry_msgs" "tf2_ros" "cv_bridge" "image_transport" "pluginlib" "rosidl_default_generators" "sensor_msgs" "generate_parameter_library")
set(aruco_transforms_BUILDTOOL_EXPORT_DEPENDS )
set(aruco_transforms_EXEC_DEPENDS "tf2" "tf2_geometry_msgs" "geometry_msgs" "tf2_ros" "cv_bridge" "image_transport" "pluginlib" "rosidl_default_generators" "sensor_msgs" "generate_parameter_library")
set(aruco_transforms_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(aruco_transforms_GROUP_DEPENDS )
set(aruco_transforms_MEMBER_OF_GROUPS )
set(aruco_transforms_DEPRECATED "")
set(aruco_transforms_EXPORT_TAGS)
list(APPEND aruco_transforms_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
