set(_AMENT_PACKAGE_NAME "ar3_hardware_interface")
set(ar3_hardware_interface_VERSION "0.0.0")
set(ar3_hardware_interface_MAINTAINER "cobot <zchampion2020@my.fit.edu>")
set(ar3_hardware_interface_BUILD_DEPENDS "hardware_interface" "pluginlib" "rclcpp" "rclcpp_lifecycle")
set(ar3_hardware_interface_BUILDTOOL_DEPENDS "ament_cmake")
set(ar3_hardware_interface_BUILD_EXPORT_DEPENDS "hardware_interface" "pluginlib" "rclcpp" "rclcpp_lifecycle")
set(ar3_hardware_interface_BUILDTOOL_EXPORT_DEPENDS )
set(ar3_hardware_interface_EXEC_DEPENDS "hardware_interface" "pluginlib" "rclcpp" "rclcpp_lifecycle")
set(ar3_hardware_interface_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(ar3_hardware_interface_GROUP_DEPENDS )
set(ar3_hardware_interface_MEMBER_OF_GROUPS )
set(ar3_hardware_interface_DEPRECATED "")
set(ar3_hardware_interface_EXPORT_TAGS)
list(APPEND ar3_hardware_interface_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
