set(_AMENT_PACKAGE_NAME "cobot_corrector")
set(cobot_corrector_VERSION "0.0.0")
set(cobot_corrector_MAINTAINER "zachc <zachchampion79@gmail.com>")
set(cobot_corrector_BUILD_DEPENDS "urdf" "tf2" "tf2_geometry_msgs" "std_msgs" "sensor_msgs" "geometry_msgs" "chess_msgs" "tf2_ros" "tf2_kdl" "orocos_kdl_vendor" "kdl_parser" "generate_parameter_library" "cv_bridge" "image_transport")
set(cobot_corrector_BUILDTOOL_DEPENDS "ament_cmake")
set(cobot_corrector_BUILD_EXPORT_DEPENDS "urdf" "tf2" "tf2_geometry_msgs" "std_msgs" "sensor_msgs" "geometry_msgs" "chess_msgs" "tf2_ros" "tf2_kdl" "orocos_kdl_vendor" "kdl_parser" "generate_parameter_library" "cv_bridge" "image_transport")
set(cobot_corrector_BUILDTOOL_EXPORT_DEPENDS )
set(cobot_corrector_EXEC_DEPENDS "urdf" "tf2" "tf2_geometry_msgs" "std_msgs" "sensor_msgs" "geometry_msgs" "chess_msgs" "tf2_ros" "tf2_kdl" "orocos_kdl_vendor" "kdl_parser" "generate_parameter_library" "cv_bridge" "image_transport")
set(cobot_corrector_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(cobot_corrector_GROUP_DEPENDS )
set(cobot_corrector_MEMBER_OF_GROUPS )
set(cobot_corrector_DEPRECATED "")
set(cobot_corrector_EXPORT_TAGS)
list(APPEND cobot_corrector_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
